### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Guenni75** [TheDeadGuy/ledvis#4]
Hi.
There is something missing in the installation instructions.
If i try this
cd ~
git clone https://github.com/jgarff/rpi_ws281x.git
sudo apt install scons swig
cd rpi_ws281x
scons
cd python
sudo -H python setup.py build
sudo -H python setup.py install

i stuck on "cd python". There is no folder python.
python --version gives me a 3.9.2. so it is installed!

Where/how must i start the installation process????

**Comment by HariComputes** [comment]
Sorry,

Didn't realise you left a problem here... 2 years ago :/

I'm updating the notes. looks like the repo changed and split the python stuff apart.

My pi died so... time to retest the instructions.

**Comment by HariComputes** [comment]
This should be sorted now
